@echo off
setlocal

REM Configuration
set "SERVER=SPR-JEOFFREY-C\SQLEXPRESS"
set "DATABASE=MESRecovery"
set "OUT_DIR=Analysis"
set "OUT_FILE=MESanalysis.csv"
set "OUT_PATH=%OUT_DIR%\%OUT_FILE%"

REM Ensure sqlcmd is available
where sqlcmd >nul 2>&1
if errorlevel 1 (
  echo ERROR: sqlcmd not found on PATH.
  echo Please install SQLCMD and retry.
  exit /b 1
)

REM Create output directory if it doesn't exist
if not exist "%OUT_DIR%" (
  mkdir "%OUT_DIR%" 2>nul
)

REM Write CSV header
> "%OUT_PATH%" echo TABLE_NAME,COLUMN_NAME,DATA_TYPE,ALLOWS_NULLS,IS_PRIMARY_KEY,IS_FOREIGN_KEY,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME

REM Query INFORMATION_SCHEMA and append to CSV with data type, nullability and PK/FK flags
sqlcmd -S "%SERVER%" -d "%DATABASE%" -h -1 -W -s "," -Q "SET NOCOUNT ON; SELECT c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE, CASE WHEN c.IS_NULLABLE = 'YES' THEN 'TRUE' ELSE 'FALSE' END AS ALLOWS_NULLS, CASE WHEN EXISTS ( SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME AND kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA AND kcu.TABLE_NAME = tc.TABLE_NAME WHERE tc.TABLE_SCHEMA = c.TABLE_SCHEMA AND tc.TABLE_NAME = c.TABLE_NAME AND kcu.COLUMN_NAME = c.COLUMN_NAME AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY' ) THEN 'TRUE' ELSE 'FALSE' END AS IS_PRIMARY_KEY, CASE WHEN fk.REFERENCED_TABLE_NAME IS NOT NULL THEN 'TRUE' ELSE 'FALSE' END AS IS_FOREIGN_KEY, ISNULL(fk.REFERENCED_TABLE_NAME, '') AS REFERENCED_TABLE_NAME, ISNULL(fk.REFERENCED_COLUMN_NAME, '') AS REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS c LEFT JOIN ( SELECT DISTINCT kcu.TABLE_SCHEMA, kcu.TABLE_NAME, kcu.COLUMN_NAME, ccu.TABLE_NAME AS REFERENCED_TABLE_NAME, ccu.COLUMN_NAME AS REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME AND tc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA AND tc.TABLE_NAME = kcu.TABLE_NAME AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY' JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc ON rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME AND rc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ccu ON ccu.CONSTRAINT_SCHEMA = rc.UNIQUE_CONSTRAINT_SCHEMA AND ccu.CONSTRAINT_NAME = rc.UNIQUE_CONSTRAINT_NAME AND ccu.ORDINAL_POSITION = kcu.ORDINAL_POSITION ) fk ON fk.TABLE_SCHEMA = c.TABLE_SCHEMA AND fk.TABLE_NAME = c.TABLE_NAME AND fk.COLUMN_NAME = c.COLUMN_NAME ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION;" >> "%OUT_PATH%"
if errorlevel 1 (
  echo ERROR: Failed to query database %DATABASE% on %SERVER%.
  exit /b 1
)

echo Export complete: %OUT_PATH%
endlocal
exit /b 0